"syscon fix"
riscy-development/riscy-os pull request #10
Opened 2023-12-10 01:27 UTC by kjhayes

It's not exactly a "fix" it's just if we tried to run on anything other than the exact QEMU setup in run.sh the "syscon" driver would fail.

syscon is just a generic set of registers but we had hardcoded access offsets and values which I'm guessing were just grabbed from OSDev or something? Now we should be able to use the reboot and/or shutdown functionality of syscon registers if they exist regardless of the SoC.

2023-12-10 01:28 UTC, kjhayes commented
Don't merge this one until the Boot Allocator get's merged, it is a branch off of that PR and uses code from it.

2023-12-14 22:44 UTC, egelja requested changes

2023-12-14 22:44 UTC, egelja commented on drivers/syscon/syscon.c
> +    .value = NULL,
this should be 0 not NULL

2023-12-14 22:44 UTC, egelja commented on drivers/syscon/syscon.c
> +    .value = NULL,
this should be 0 not NULL

2023-12-14 22:44 UTC, egelja commented on kernel/of/fdt.c
> +            if (phandle == fdt_prop_get_cell(phandle_prop, 0)) {
```suggestion
            if (fdt_prop_get_cell(phandle_prop, 0) == phandle) {
```

2023-12-14 22:44 UTC, egelja commented on drivers/syscon/syscon.c
> +    uint32_t offset = fdt_prop_get_cell(offset_prop, 0);
probably should check that `offset < syscon_size`

2023-12-14 22:44 UTC, egelja commented on drivers/syscon/syscon.c
> +        // All one's (effectively no mask)
```suggestion
        // All ones (no mask)
```

2023-12-15 16:20 UTC, egelja approved these changes
lgtm

2023-12-15 16:29 UTC, merged