Add syscon functions
riscy-development/riscy-os pull request #7
Opened 2023-12-08 23:17 UTC by egelja

Try it out:
1. Run the kernel
2. Press `^`
3. Press `&`

2023-12-08 23:32 UTC, kjhayes requested changes
I guess it's okay for now but the main thing is `syscon` definitely doesn't belong in "kernel/of", it might be time to make "kernel/drivers" or "kernel/dev/" or just "drivers"

2023-12-08 23:32 UTC, kjhayes commented on include/kernel/of/syscon.h
This doesn't belong in the "kernel/of" directory, it's a really primitive driver and "of" is for OpenFirmware stuff

2023-12-08 23:32 UTC, kjhayes commented on docs/arch.md
This file is gonna get loooooooooooong but I'm glad to see we're planning ahead

2023-12-08 23:32 UTC, kjhayes commented on docs/arch.md
Also, theoretically it should be drivers which try to call `register_early_putchar` not necessarily the architecture

2023-12-08 23:33 UTC, kjhayes commented
Overall really cool, I'm glad the FDT stuff wasn't too awful to use

2023-12-09 02:44 UTC, egelja commented on docs/arch.md
Ya I guess it would be better to says "initializes basic drivers" right?

2023-12-09 19:34 UTC, kjhayes commented on drivers/syscon/syscon.c
I'm gonna be pushing a commit to `fdt_mem` soon which should make this a lot simpler so one of us should come back and use the new functions in `fdt.h`

2023-12-09 19:34 UTC, kjhayes commented on drivers/syscon/syscon.c
But looks good

2023-12-09 19:37 UTC, kjhayes approved these changes

2023-12-09 22:25 UTC, merged